name: google_maps_cluster_manager
description: Simple Flutter clustering library for Google Maps based on Geohash.
version: 0.1.0
author: Baptiste Pillon <baptiste.pillon@gmail.com>
homepage: https://github.com/bpillon/google_maps_cluster_manager

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  geohash: ^0.2.1
  google_maps_flutter: ^0.5.22
  geoflutterfire: 
    git:
      url: git@github.com:theonlyandreas/GeoFlutterFire.git

dev_dependencies:
  flutter_test:
    sdk: flutter
